-- MySQL Script generated by MySQL Workbench
-- lun 04 jun 2018 16:14:04 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema metodologias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema metodologias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metodologias` DEFAULT CHARACTER SET utf8 ;
USE `metodologias` ;

-- -----------------------------------------------------
-- Table `metodologias`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodologias`.`tipos` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metodologias`.`metodologias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodologias`.`metodologias` (
  `idmetodologia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `idtipo` INT NOT NULL,
  PRIMARY KEY (`idmetodologia`),
  INDEX `fk_metodologias_tipo1_idx` (`idtipo` ASC),
  CONSTRAINT `fk_metodologias_tipo1`
    FOREIGN KEY (`idtipo`)
    REFERENCES `metodologias`.`tipos` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metodologias`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodologias`.`categorias` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `pregunta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metodologias`.`criterios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodologias`.`criterios` (
  `idcriterio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `idcategoria` INT NOT NULL,
  PRIMARY KEY (`idcriterio`),
  INDEX `fk_criterios_categorias1_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_criterios_categorias1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `metodologias`.`categorias` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metodologias`.`metodologias_criterios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodologias`.`metodologias_criterios` (
  `idmetodologia` INT NOT NULL,
  `idcriterio` INT NOT NULL,
  INDEX `fk_metodologias_criterios_metodologias_idx` (`idmetodologia` ASC),
  INDEX `fk_metodologias_criterios_criterios1_idx` (`idcriterio` ASC),
  CONSTRAINT `fk_metodologias_criterios_metodologias`
    FOREIGN KEY (`idmetodologia`)
    REFERENCES `metodologias`.`metodologias` (`idmetodologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metodologias_criterios_criterios1`
    FOREIGN KEY (`idcriterio`)
    REFERENCES `metodologias`.`criterios` (`idcriterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
